### ISSUE TITLE
Feature Request - progress callback

### ISSUE THREAD

**Issue by bigt11** [fastrde/cordova-plugin-fastrde-md5#4]
Any way to get a callback function on progress of a chunk.  I have large files to check and it takes about 40 seconds.  Would be cool if we could get a callback function option upon completion of  a chunk.  Maybe it  could pass current chunk and how many chunks total so some sort of progress can be displayed.  -Thanks

**Comment by fastrde** [comment]
yes it's possible.You have to get the filesize and call the process-callback-method in die while loops (after md5.update and CC_MD5_Update). In https://github.com/fastrde/cordova-plugin-fastrde-mqtt/blob/master/src/android/MQTTPlugin.java line 84ff you can find an example how to call javascript callback-functions functions.Look at https://github.com/fastrde/cordova-plugin-fastrde-mqtt/blob/master/src/ios/CDVMQTTPlugin.m line 149ff for an iOS example.

You can also pass the name of the javascript-callback function as parameter so you don't have to hardcode it.

Pullrequest appreciated.
